//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  7 2017 20:36:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>
#import "DVTSourceCodeSymbolKind.h"

@class IDESourceKitUIDSet, NSAttributedString, NSString;

@interface IDESourceKitCompletionItem : NSObject
{
    IDESourceKitUIDSet *_UID;
    double _priority;
    double _fuzzyMatchingScore;
}

@property(nonatomic) double fuzzyMatchingScore; // @synthesize fuzzyMatchingScore=_fuzzyMatchingScore;
@property(nonatomic) double priority; // @synthesize priority=_priority;
- (id)description;
@property(readonly) BOOL notRecommended;
- (void)setPriority;
@property(readonly) DVTSourceCodeSymbolKind *symbolKind;
@property(readonly) NSAttributedString *descriptionText;
@property(readonly, copy) NSString *parentText;
@property(readonly) NSString *completionText;
@property(readonly) NSString *displayType;
@property(readonly) NSString *displayText;
@property(readonly) NSString *name;

@end

